-- V6: Add deleted column for Soft Delete support in major entities

ALTER TABLE users ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE gathering ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE itinerary ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE comment ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE gathering_post ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
